all:
  children:
    debian:
      hosts:
        debian-server-1:
          ansible_host: 192.168.1.152
        debian-server-2:
          ansible_host: 192.168.1.153
        debian-server-3:
          ansible_host: 192.168.1.156
      vars:
        ansible_user: 'root'
        ansible_connection: 'ssh'
        package_name: "sl"
    
    redhat:
      hosts:
        redhat-server-1:
          ansible_host: 192.168.1.11
        redhat-server-2:
          ansible_host: 192.168.1.13
      vars:
        ansible_user: 'root'
        ansible_connection: 'ssh'
        package_name: "sl"
