debian:
  hosts:
    proxmox:
      ansible_host: 192.168.1.10
      ansible_user: 'root'
      ansible_password: 'admin'
      ansible_connection: 'ssh'

redhat:
  hosts:
    proxmox:
      ansible_host: 192.168.1.11
      ansible_user: 'root'
      ansible_password: 'admin'
      ansible_connection: 'ssh'