# Debian Update & Upgrade
---

- name: Update Debian systems
  apt:
    update_cache: yes
  when: "'debian' in group_names"

- name: List upgradeable packages in Debian
  command: apt list --upgradable
  register: debian_upgrades
  when: "'debian' in group_names"

- name: Debian'da yükseltilebilir paketleri göster
  debug:
    msg: "{{ debian_upgrades.stdout }}"
  when: "'debian' in group_names"

- name: Upgradeable packages in DebianShow Debian packages upgrade in order
  apt:
    name: "{{ item.split('/')[0] }}"
    state: latest
  loop: "{{ debian_upgrades.stdout_lines[1:] | map('split', '/') | map('first') | list }}"
  when: "'debian' in group_names"
  register: debian_upgrade_results
  notify:
    - Package upgraded

- name: Show Debian upgrade results
  debug:
    var: debian_upgrade_results
  when: "'debian' in group_names"

- name: Package upgraded (Debian)
  debug:
    msg: "Paket '{{ item }}' başarıyla yükseltildi."
  with_items: "{{ debian_upgrade_results.results | map(attribute='item') | list }}"
  when: "'debian' in group_names"
