# Red Hat Update & Upgrade
---

- name: Update RedHat systems
  yum:
    update_cache: yes
  when: "'redhat' in group_names"

- name: List upgradeable packages in RedHat
  yum:
    list: updates
  register: redhat_upgrades
  when: "'redhat' in group_names"

- name: Show upgradable packages in RedHat
  debug:
    msg: "Paket '{{ item }}' güncelleniyor..."
  loop: "{{ redhat_upgrades.results | map(attribute='name') | list }}"
  when: "'redhat' in group_names"

- name: Upgrade RedHat packages in order
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ redhat_upgrades.results | map(attribute='name') | list }}"
  when: "'redhat' in group_names"
  register: redhat_upgrade_results
  notify:
    - Package upgraded

- name: Show RedHat upgrade results
  debug:
    var: redhat_upgrade_results
  when: "'redhat' in group_names"