# Red Hat Sistemleri İçin Görevler
---

- name: Update Red Hat systems
  yum:
    update_cache: yes
  when: "'redhat' in group_names"

- name: List upgradeable packages in Red Hat
  command: yum list updates
  register: redhat_upgrades
  when: "'redhat' in group_names"

- name: Show upgradable packages on Red Hat
  debug:
    msg: "{{ redhat_upgrades.stdout }}"
  when: "'redhat' in group_names"

- name: Upgrade Red Hat packages in order
  yum:
    name: "{{ item.split('.')[0] }}"
    state: latest
  loop: "{{ redhat_upgrades.stdout_lines[1:] | map('split', '.') | map('first') | list }}"
  when: "'redhat' in group_names"
  register: redhat_upgrade_results
  notify:
    - Paket yükseltildi (Red Hat)

- name: Show Red Hat upgrade results
  debug:
    var: redhat_upgrade_results
  when: "'redhat' in group_names"

- name: Package upgraded (Red Hat)
  debug:
    msg: "Paket '{{ item }}' başarıyla yükseltildi."
  with_items: "{{ redhat_upgrade_results.results | map(attribute='item') | list }}"
  when: "'redhat' in group_names"