# Red Hat Update & Upgrade
---

- name: Red Hat sistemlerini güncelle
  yum:
    update_cache: yes
  when: "'redhat' in group_names"

- name: Red Hat'da yükseltilebilir paketleri listele
  yum:
    list: updates
  register: redhat_upgrades
  when: "'redhat' in group_names"

- name: Paket güncellenmeden önce bilgi ver (Red Hat)
  debug:
    msg: "Paket '{{ item }}' güncelleniyor..."
  loop: "{{ redhat_upgrades.results | map(attribute='name') | list }}"
  when: "'redhat' in group_names"

- name: Red Hat paketlerini sırayla yükselt
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ redhat_upgrades.results | map(attribute='name') | list }}"
  when: "'redhat' in group_names"
  register: redhat_upgrade_results
  notify:
    - Paket yükseltildi (Red Hat)

- name: Red Hat yükseltme sonuçlarını göster
  debug:
    var: redhat_upgrade_results
  when: "'redhat' in group_names"