# Steps by Step
---

- name: "Ubuntu Update" 
  ansible.builtin.import_tasks: 01_debian_update.yml

- name: "RedHat Update" 
  ansible.builtin.import_tasks: 02_redhat_update.yml

- name: "Install Package" 
  ansible.builtin.import_tasks: 03_install_package.yml


